variables:
  REGISTRY_ADDRESS: registry.jajiga.com:5000
  IMAGE_DIR: $REGISTRY_ADDRESS/shorjiga/$CI_COMMIT_REF_NAME

stages:
  - test
  - build
  - push

test:
  stage: test
  image: golang:latest
  services:
    - name: postgres:14
      alias: pgsql
    - name: redis:alpine
      alias: redis
  variables:
    POSTGRES_DB: shorjiga_test
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_HOST_AUTH_METHOD: trust
    REDIS_HOST: redis

    DB_HOST: pgsql
    DB_NAME: shorjiga_test
    DB_USER: postgres
    DB_PASSWORD: password
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test
  allow_failure: true

build:
  stage: build
  image: golang:latest
  script:
    - go build -o main .
  allow_failure: true
  artifacts:
    paths:
      - main
  only:
    - main
    - merge_requests

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u ${registry_user} -p ${registry_pass} ${REGISTRY_ADDRESS}
    - docker pull $IMAGE_DIR:latest || true
    - docker build --cache-from $IMAGE_DIR:latest --file ./Dockerfile  --tag $IMAGE_DIR:latest .
    - docker push $IMAGE_DIR:latest
    - docker image prune --all --force
  only:
    - main
    - merge_requests
